name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'
        dependency-version: [prefer-stable]
        grpc-version:
          - '1.25.*'
          - '1.26.*'
          - '1.27.*'
          - '1.30.*'
          - '1.34.*'

    name: ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.grpc-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Install GRPC
        run: |
          composer require --${{ matrix.dependency-version }} --prefer-dist --no-interaction grpc/grpc:${{ matrix.grpc-version }}

      - name: Execute tests
        run: ./vendor/bin/phpunit tests
